### ISSUE TITLE
你好 我想问下Windows下能用吗

### ISSUE THREAD

**Issue by lofyol** [PanJinquan/Human-Pose-Estimation-Lite-cpp#1]

**Comment by PanJinquan** [comment]
目前只在Linux平台测试通过，原则上windows也是支持的，我没有测试，你可以试试看哦

**Comment by PanJinquan** [comment]
你好，很抱歉，我没有在Windows测试过，不过从依赖的库来说，Linux+Windows+Android都应该是支持的

**Comment by lofyol** [comment]
> 你好，很抱歉，我没有在Windows测试过，不过从依赖的库来说，Linux+Windows+Android都应该是支持的


好的谢谢大佬，有机会我试试
